import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class CategoryIconsList {
  List<IconData> iconsList = [
    Icons.shopping_cart,
    Icons.local_phone,
    Icons.edit,
    Icons.people,
    Icons.search,
    Icons.computer,
    Icons.access_alarm,
    Icons.favorite,
    FontAwesomeIcons.star,
    Icons.insert_drive_file,
    Icons.mail,
    Icons.shopping_cart,
    Icons.restaurant,
    FontAwesomeIcons.walking,
    FontAwesomeIcons.graduationCap,
    FontAwesomeIcons.ambulance,
    FontAwesomeIcons.school,
    Icons.fitness_center,
    Icons.cake,
    Icons.free_breakfast,
    Icons.comment,
    FontAwesomeIcons.tshirt,
    FontAwesomeIcons.itunesNote,
    FontAwesomeIcons.map,
    FontAwesomeIcons.tasks,
    Icons.colorize,
    FontAwesomeIcons.book,
    Icons.camera_alt,
    FontAwesomeIcons.moneyBill,
    FontAwesomeIcons.biking,
    Icons.cast_for_education,
    FontAwesomeIcons.heartbeat,
    FontAwesomeIcons.dog,
    Icons.work,
    Icons.weekend,
    Icons.home,
    Icons.directions_car,
    Icons.directions_bus,
    Icons.search,
    Icons.thumbs_up_down,
    Icons.wb_cloudy,
    Icons.wb_sunny,
    FontAwesomeIcons.trash,
  ];
}
